services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    # restart: always
    links:
      - mongodb
      - meilisearch
      - rag_api
    extra_hosts: # if you are running APIs on docker you need access to, you will need to uncomment this line and next
      - "host.docker.internal:host-gateway"

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/home/node/.ssh-localhost:ro

    # Use a non-root user for all processes - See https://aka.ms/vscode-remote/containers/non-root for details.
    user: "${UID:-1000}:${GID:-1000}"

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  

  mongodb:
    container_name: chat-mongodb
    image: mongo:latest
    # restart: always
    expose:
      - 27017
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    # restart: always
    expose:
      - 7700
    env_file:
      - .env
    volumes:
      - ./meili_data_v1.5:/meili_data
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    # restart: always
    depends_on:
      - vectordb
    expose:
      - 8000
    environment:
      - RAG_PORT=${RAG_PORT:-8000}
      - DB_HOST=vectordb
      - DB_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      # - VECTOR_DB_TYPE=atlas-mongo
      # - ATLAS_MONGO_DB_URI=${MONGO_URI}
      # - COLLECTION_NAME=ragvectors
      # - ATLAS_SEARCH_INDEX=vecid
    env_file:
      - .env
  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata2: