services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: node
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    restart: always
    links:
      - mongodb
      - meilisearch
      - vectordb
      - rag_api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/workspaces:cached
      - ${HOME}${USERPROFILE}/.ssh:/home/node/.ssh-host:ro
      - ${HOME}${USERPROFILE}/.gnupg:/home/node/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${HOME}${USERPROFILE}/.vscode/extensions:/home/node/.vscode-server/extensions
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000

    # Use a non-root user for all processes - See https://aka.ms/vscode-remote/containers/non-root for details.
    user: node:node

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    expose:
      - 7700
    environment:
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - ./meili_data_v1.7:/meili_data
    env_file:
      - .env.dev
  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: always
    links:
      - vectordb
    expose:
      - 8000
    environment:
      - DB_HOST=vectordb
    depends_on:
      - vectordb
    env_file:
      - .env.dev
